name: Deployment workflow
on:
  push:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: update code in server
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /root/ejercicios
          git pull origin master
        host: ${{ secrets.HOST }}
        user: root
        port: 22
        Key: "${{secrets.SSH_KEY}}"
        args: "-tt"

    - name: build code in server
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /root/ejercicios
          go clean
          go build
          ls -l
        host: ${{ secrets.HOST }}
        user: root
        port: 22
        Key: "${{secrets.SSH_KEY}}"
        args: "-tt"

    - name: restart app
      uses: fifsky/ssh-action@master
      with:
        command: |
          systemctl restart saulapp
          systemctl status saulapp
        host: ${{ secrets.HOST }}
        user: root
        port: 22
        Key: "${{secrets.SSH_KEY}}"
        args: "-tt"
      
