name: Deployment workflow
on:
  push:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # - name: ls -a via ssh
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: root
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       cd /tmp
    #       ls -a
    #     # args: "-tt -vvv"
    
    - name: ls with ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /root
          pwd -P
          ls -la
        host: ${{ secrets.HOST }}
        user: root
        port: 22
        Key: "${{secrets.SSH_KEY}}"
        args: "-tt"

    # - name: clone repo
    #   uses: fifsky/ssh-action@master
    #   with:
    #     command: |
    #       git clone https://github.com/spinales/ejercicios.git
    #     host: ${{secrets.HOST}}
    #     user: root
    #     Key: ${{secrets.SSH_KEY}}
    #     args: "-tt"
    
    # - name: ls with ssh
    #   uses: fifsky/ssh-action@master
    #   with:
    #     command: |
    #       ls -la
    #     host: ${{secrets.HOST}}
    #     user: root
    #     Key: ${{secrets.SSH_KEY}}
    #     args: "-tt"
